project_id = "dkopohqiihhxmbjhzark"

[functions.send-otp-email]
verify_jwt = false

[functions.verify-otp-and-reset-password]
verify_jwt = false
[functions.send-restock-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-restock-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-restock-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-restock-notification/*.html" ]
